config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  devise_for :users, skip: %i(registrations passwords)

  resources :streams, only: :show
  resources :tracks
  resources :playlists
  get '/playlists/:id/download' => 'playlists#download', as: :download_playlist

  resources :users, except: [:index, :create, :edit, :new] do
    collection do
      get 'me'
      patch 'reindexing'
    end
  end
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  name       :string           not null
#  token      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_playlists_on_name  (name) UNIQUE
#

class Playlist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tracks
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  include PlaylistTracksUpdater
  include PlaylistGenerator

  before_action :authenticate_user!
  before_action :fetch_playlist, only: %i(show edit update download destroy)

  def index
    @playlists = current_user.playlists
  end

  def edit
    @tracks = current_user.tracks
  end

  def update
    @playlist.assign_attributes(playlist_params)
    update_tracks(params[:playlist][:track])
    if @playlist.save
      redirect_to playlists_path
    else
      flash[:alert] = playlist.errors.full_messages
      redirect_to edit_playlist_path(@playlist.id)
    end
  end

  def new
    @playlist = Playlist.new
    @tracks = Track.all
  end

  def create
    @playlist = Playlist.new(playlist_params.merge(user: current_user, token: SecureRandom.hex))
    update_tracks(params[:playlist][:track])
    if @playlist.save
      redirect_to playlists_path
    else
      flash[:alert] = @playlist.errors.full_messages
      redirect_to new_playlist_path
    end
  end

  def download
    case params[:extension]
    when 'm3u8'
      send_data m3u8_playlist,
        filename: "#{@playlist.name}.m3u8",
        type: 'text/plain',
        disposition: 'attachment'
    when 'xspf'
      template = Tilt.new('app/views/playlists/download.xml.builder')
      send_data template.render(self),
        filename: "#{@playlist.name}.xspf",
        type: 'text/plain',
        disposition: 'attachment'
    end
  end

  def destroy
    @playlist.destroy!
    redirect_to playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :token)
  end

  def fetch_playlist
    @playlist = current_user.playlists.find(params[:id])
  end
end

app/views/playlists/edit.html.slim
div class="row"
  = form_for @playlist do |f|
    div class="panel-container"
      div class="panel-content"

        div class="row collapse"
          /! name
          div class="columns small-12 medium-3"
            = label_tag :name, 'Name', class: 'prefix'

          div class="columns small-12 medium-9"
            = text_field_tag 'playlist[name]', @playlist.name, required: true

        div class="row collapse"
          /! token
          div class="columns small-12 medium-3"
            = label_tag :token, 'Token', class: 'prefix'

          div class="columns small-12 medium-8"
            = text_field_tag 'playlist[token]', @playlist.token, required: true, readonly: true

          div class="columns small-12 medium-1"
            = text_field_tag :refresh, 'Refresh', class: 'button small postfix', type: :button, onclick: 'refreshToken("playlist_token");'

        div class="row collapse"
          div class="columns small-12 medium-6"
            ul class="button-group radius"
              li = link_to 'Cancel', playlists_path, class: 'button secondary small'
              li = text_field_tag nil, 'Update', type: :submit, class: 'button success small'

        div class="row collapse"
          = render 'shared/tracks'

        div class="row collapse"
          div class="columns small-12 medium-6"
            ul class="button-group radius"
              li = link_to 'Cancel', playlists_path, class: 'button secondary small'
              li = text_field_tag nil, 'Update', type: :submit, class: 'button success small'

app/views/playlists/index.html.slim
div class="row"
  table role="grid"
    thead
      tr
        th width="200" Name
        th width="200" Number of tracks
        th width="300"

    tbody
      - @playlists.each do |playlist|
        tr
          td = playlist.name
          td = playlist.tracks.count
          td
            a href="#" data-dropdown="drop" aria-controls="drop" aria-expanded="false" class="button tiny info radius dropdown"
              i class="icon-download"
              |  Download

            ul.dropdown id="drop" class="f-dropdown" role="menu" aria-hidden="false" tabindex="-1"
              li = link_to 'M3U8', download_playlist_path(playlist.id, extension: :m3u8)
              li = link_to 'XSPF', download_playlist_path(playlist.id, extension: :xspf)

            = link_to 'Edit', edit_playlist_path(playlist.id), class: 'button tiny info radius'
            = link_to 'Delete', playlist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button alert tiny radius'

  = link_to '+', new_playlist_path, class: 'button secondary small radius'

app/views/playlists/new.html.slim
div class="row"
  = form_for @playlist do |f|
    div class="panel-container"
      div class="panel-content"

        div class="row collapse"
          div class="columns small-12 medium-3"
            = label_tag :name, 'Name', class: 'prefix'

          div class="columns small-12 medium-9"
            = text_field_tag "playlist[name]", nil, required: true

        div class="row collapse"
          ul class="button-group radius"
            li = link_to 'Cancel', playlists_path, class: 'button secondary small'
            li = text_field_tag nil, 'Create', type: :submit, class: 'button success small'

        div class="row collapse"
          = render 'shared/tracks'

        div class="row collapse"
          ul class="button-group radius"
            li = link_to 'Cancel', playlists_path, class: 'button secondary small'
            li = text_field_tag nil, 'Create', type: :submit, class: 'button success small'