config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  devise_for :users, skip: %i(registrations passwords)

  resources :streams, only: :show
  resources :tracks
  resources :playlists
  get '/playlists/:id/download' => 'playlists#download', as: :download_playlist

  resources :users, except: [:index, :create, :edit, :new] do
    collection do
      get 'me'
      patch 'reindexing'
    end
  end
end

app/views/layouts/_topbar.html.slim
nav class="row" role="navigation"
  div class="title-area left"
    h1
      = link_to 'Shiva', root_path, data: { 'target': 'home' }

  /! Right Nav Section
  div class="right"
    br
    - if current_user
      current_user.reload
      div class="avatar"
        a data-dropdown="dropdownMenu" href="#" class="has-dropdown"
          i class="icon-shuffle size-title"
          span class="hide-for-small-only"
          = ' ' + current_user.username.humanize
    - else
      /! Use smooth scrolling only when on the same page
      - if request.original_fullpath != new_user_session_path
          div class="right"
            = link_to new_user_session_path, class:'login button small radius', data: { 'target': 'login' } do
              i class="icon-enter small"
              |  Log In
  br
  br
  br
  - if current_user
    div
      ul class="button-group radius"
        - case request.original_fullpath
          - when tracks_path
            li
              = link_to 'Playlist', playlists_path, class: 'button tiny secondary'
          - when playlists_path
            li
              = link_to 'Tracks', tracks_path, class: 'button tiny secondary'
          - else
            li
              = link_to 'Tracks', tracks_path, class: 'button tiny secondary'
            li
              = link_to 'Playlist', playlists_path, class: 'button tiny secondary'

/! logout
div class="row dropdown-menu-container"
  ul.dropdown id="dropdownMenu" class="f-dropdown" aria-hidden="true"
    li
      = link_to me_users_path, id: 'profile' do
        i class="icon-cogs"
        |  Settings
    li
      = link_to destroy_user_session_path, method: :delete, id: 'logout' do
        i class="icon-exit"
        |  Logout

app/views/layouts/application.html.slim
doctype html
html
  head
    title Shiva
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = javascript_include_tag 'vendor/modernizr'
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags

body class="antialiased"

header
  = render 'layouts/topbar'

== yield

footer
  div class="row"
    div class="columns large-6 legal right"
      = link_to 'Shiva', 'https://github.com/mdouchement/shiva', target:'_blank'